name: Deploy Workflow
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:  
      - name: Include Template
        run: |
          ls -al
          pwd
          